name: 'build' 
on: 
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v1
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: stuartleeks/devcontainer-build-run@v0.1
        with:
          imageName: ghcr.io/stuartleeks/devcontainer-build-run-demo/dev-container
          runCmd: make ci
          push: filter
          refFilterForPush: refs/head/main
          eventFilterForPush: |
            push
            workflow_dispatch
